# -*- coding: utf-8 -*-
"""listy_krotki_potęga_pierwiastek.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nH5EHj_24Ot-X2fqY6II63tYMQ9LDbEA

Napisać program, w którym tworzona jest lista liczb nieparzystych z zakresu podanego przez użytkownika [a,b]. Przy czym użytkownik może podać dowolne wartości a oraz b (można założyć, że całkowite dodatnie), należy jednak zadbać, aby lista uzupełniona była tylko liczbami nieparzystymi. Np. dla a=5 i b=10 lista: [5,7,9], natomiast dla a=2 i b=9 lista: [3,5,7,9]. Następnie należy zmodyfikować listę tak, aby w miejscu wartości znajdowała się krotka, w której jest: wartość, 2 do potęgi wartości, pierwiastek z wartości. Przykładowo dla: listy: [5,7,9] wynikiem jest: lista: [(5, 32, 2.23606797749979), (7, 128, 2.6457513110645907), (9, 512, 3.0)].
"""

from math import sqrt

a = int(input("podaj pierwszą liczbę całkowitą dodatnią: "))
b = int(input("podaj drugą liczbę całkowitą dodatnią: "))

odd_number_list = []

for number in range(a,b+1):
    if number%2 != 0:
        odd_number_list.append(number)

print(odd_number_list)

list2 = []
for el in odd_number_list:
    tupl = (el, 2**el, sqrt(el))
    list2.append(tupl)

print(list2)