# -*- coding: utf-8 -*-
"""Palindrom_sprawdzanie.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wM8vfZPETN-BC9c4OVPAhrSqKsdLsP9N

Napisać program, który wczytuje od użytkownika ciąg znaków, a następnie sprawdza, czy podany ciąg jest palindromem.
"""

ciag_zn = input("napisz słowo lub zdanie: ")

ciag_zn = ciag_zn.replace(",","").replace(".","")
while " " in ciag_zn:
    ciag_zn = ciag_zn.replace(" ","")
ciag_zn = ciag_zn.lower()

if ciag_zn == ciag_zn[::-1]:
    print("podany ciąg znaków jest palindromem")
else:
    print("podany ciąg znaków nie jest palindromem")