# -*- coding: utf-8 -*-
"""pliki_tekstowe_wczytanie_danych_przeliczenie_lat_do_emerytury_zapis_do_nowych_plików.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZTlIki2pXP2w3qUt-b0yiPUQRPHc0n-P

Napisać funkcję def emerytura(nazwaPliku), która wczyta z pliku o podanej nazwie dane pracowników zapisane w kolejnych wierszach w następujący sposób: Imię Nazwisko Płeć Wiek

Przykład:

Tomasz Nowak M 45

Marta Ziobro K 42

Jan Kowalski M 27

Ewelina Tusk K 59

Następnie funkcja dla każdego pracownika powinna wyznaczyć ile lat pozostało do jego emerytury. Wyniki należy zapisać w następujący sposób:

Nazwisko Imię ”Lata do emerytury”

Przykład:

Nowak Tomasz 20

Kowalski Jan 38

Wyniki dla kobiet należy zapisać w pliku o nazwie ”kobiety.txt”, natomiast wyniki dla mężczyzn należy zapisać w pliku ”mezczyzni.txt”.
"""

def emerytura(nazwaPliku):
    
    lines = open(nazwaPliku, "r").readlines()   

    fileWomen = open("kobiety.txt", "w")
    fileMen = open("mezczyzni.txt", "w")

    for line in lines:     
        line = line.split()
        name = line[0]
        surname = line[1]
        sex = line[2]
        age = int(line[3])

        if sex == "M":
            to_retirement = 65 - age
            fileMen.write(f"{surname} {name} {to_retirement}\n")
        if sex == "K":
            to_retirement = 60 - age
            fileWomen.write(f"{surname} {name} {to_retirement}\n")

    fileWomen.close()
    fileMen.close()

emerytura("pracownicy.txt")