# -*- coding: utf-8 -*-
"""Pliki_tekstowe_znajdź_słowo_w_pliku1_zapisz_całą_linię_w_pliku2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ABLKwi30wqv0ebJ3xXwJM9cr995mKldn

Napisać funkcję:

def szukaj(nazwaPlikWe, nazwaPlikWy, slowo):

której zadaniem jest znalezienie wszystkich wierszy w pliku, które zawierają szukane słowo. Wszystkie wiersze, które zawierają słowo powinny zostać zapisane w
pliku wynikowym wraz z nr wiersza (z pierwszego pliku). Nazwa pierwszego pliku zapamiętana jest w parametrze nazwaPlikWe, nazwa pliku wynikowego podana jest w parametrze nazwaPlikWy, natomiast szukane słowo w parametrze slowo.

Przykład - plik wejściowy:

Ala ma jutro egzamin z biologii.

Jan myje auto.

Eh, jutro kolejny egzamin.

Nie lubie polityki.

Jeżeli szukanym słowem byłoby ”egzamin”, to plik wynikowy powinien wyglądać następująco:

1: Ala ma jutro egzamin z biologii.

3: Eh, jutro kolejny egzamin.
"""

word = str(input("Wpisz słowo, które szukasz: "))

def szukaj(NazwaPlikWe,nazwaPlikWy,word):

    lines = open(NazwaPlikWe).readlines()

    nazwaPlikWy = open("plik_wynikowy.txt","w") 

    counter_lines = 0
    for line in lines:
        counter_lines += 1
        if word in line: 
            nazwaPlikWy.write(f"{counter_lines} {line}")
    nazwaPlikWy.close()


szukaj("dane.txt","plik_wynikowy.txt",word)