# -*- coding: utf-8 -*-
"""slowniki_zmiana_liczby_na_zapis_slowny.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xluc6KX_2FW-GPizVrFkUgRHtftOessz

Z zastosowaniem słowników należy napisać funkcję, dzięki które można dokonać
zmiany liczby podanej przez parametr (w postaci int) na zapis słowny tej liczby.
Można założyć, że liczba zawsze będzie mniejsza niż milion.
"""

def zmiana_l(parametr):

    klucze_jednosci = [el for el in range(1,11)]        
    for el in range(len(klucze_jednosci)):              
        el = str(el)                    
    
    klucze_nascie = [el for el in range(11,20)]
    for el in range(len(klucze_nascie)):
        el = str(el)
    
    klucz_dziesci = [el for el in range(20,100,10)]
    for el in range(len(klucz_dziesci)):
        el = str(el)
    
    klucz_setki = [el for el in range(100,1000,100)]
    for el in range(len(klucz_setki)):
        el = str(el)
    klucz_tys = ["1000"]

    wartosc_jednosci = ["jeden", "dwa", "trzy", "cztery", "pięć", "sześć", "siedem", "osiem", "dziewięć", "dziesięć"]
    wartosc_nascie = ["jedenaście", "dwanaście", "trzynascie", "czternascie", "piętnaście", "szesnaście", "siedemnaście", "osiemnaście", "dziewiętnaście"]
    wartosc_dziesci = ["dwadzieścia", "trzydzieści", "czterdzieści", "pięćdziesiąt", "sześćdziesiąt", "siedemdziesiąt", "osiemdziesiąt", "dziewięćdziesiąt"]
    wartosc_setki = ["sto", "dwieście", "trzysta", "czterysta", "pięćset", "sześćset", "siedemset", "osiemset", "dziewięćset"]
    wartosc_tys = ["tysiąc"]

    slownik = {}


    for el1, el2 in zip(klucze_jednosci,wartosc_jednosci):
        slownik[el1] = el2                                  
    for el3,el4 in zip(klucze_nascie,wartosc_nascie):
        slownik[el3] = el4
    for el5,el6 in zip(klucz_dziesci,wartosc_dziesci):
            slownik[el5] = el6
    for el7,el8 in zip(klucz_setki,wartosc_setki):
            slownik[el7] = el8
    for el9,el10 in zip(klucz_tys,wartosc_tys):
            slownik[el9] = el10


#rozkładanie liczby na części:

    parametr2 = parametr
    while parametr2 != 0:
        jednosc = parametr%10       
        parametr2 = parametr//10     
        
        dziesiatki = parametr2%10 * 10
        if dziesiatki < 20:
            dziesiatki_nascie = parametr2%10 * 10 + jednosc
        parametr2 = parametr2//10
        
        setki = parametr2%10 * 100
        parametr2 = parametr2//10
        
        tysiace = parametr2%10
        
        reszta_dziel_dzies_tys = parametr2%10
        parametr2 = parametr2//10
        tysiace_dzies = parametr2%10 *10
        if tysiace_dzies < 20:
            tysiace_dzies_nascie = parametr2%10 * 10 + tysiace
        
        parametr2 = parametr2//10
        tysiace_set = parametr2%10 *100
        parametr2 = parametr2//10
  
    
    lista_slow = []

#JEDNOŚCI
    if jednosc != 0:
        jednosci_slownie = slownik[jednosc]
    if parametr != 0 and parametr < 10:
        lista_slow.append(jednosci_slownie)

#LICZBY MIĘDZY 10 A 20 (NAŚCIE)
    if dziesiatki != 0 and dziesiatki < 20:
        dziesiatki_slownie = slownik[dziesiatki_nascie]
        lista_slow.insert(0,dziesiatki_slownie)

#DZIESIĄTKI
    if dziesiatki != 0 and dziesiatki >= 20:
        dziesiatki_slownie = slownik[dziesiatki]
        lista_slow.insert(0,dziesiatki_slownie)
        if jednosc != 0:
            lista_slow.insert(1,jednosci_slownie)

#SETKI
    if setki != 0 and dziesiatki != 0:
        setki_slownie = slownik[setki]
        lista_slow.insert(0,setki_slownie)
    if setki != 0 and dziesiatki == 0 and jednosc == 0:
        setki_slownie = slownik[setki]
        lista_slow.insert(0, setki_slownie)
    if setki != 0 and dziesiatki == 0 and jednosc != 0:
        setki_slownie = slownik[setki]
        lista_slow.insert(0,setki_slownie)
        lista_slow.append(jednosci_slownie)

#TYSIĄCE
    if setki == 0:
        if tysiace != 0 and tysiace < 2 and dziesiatki != 0:
            tysiace_slownie = "tysiąc"
            lista_slow.insert(0,tysiace_slownie)
        if tysiace != 0 and tysiace < 2 and dziesiatki == 0 and jednosc == 0:
            tysiace_slownie = "tysiąc"
            lista_slow.insert(0,tysiace_slownie)
        if tysiace != 0 and tysiace < 2 and dziesiatki == 0 and jednosc != 0:
            tysiace_slownie = "tysiąc"
            lista_slow.insert(0,tysiace_slownie)
            lista_slow.append(jednosci_slownie)
    if setki != 0:
        if tysiace != 0 and tysiace < 2:
            tysiace_slownie = "tysiąc"
            lista_slow.insert(0,tysiace_slownie)

    if setki == 0:
        if tysiace != 0 and tysiace >= 2 and tysiace < 5 and dziesiatki != 0:
           tysiace_slownie = slownik[tysiace] + " tysiące"
           lista_slow.insert(0,tysiace_slownie)
        if tysiace != 0 and tysiace >= 2 and tysiace < 5 and dziesiatki == 0 and jednosc == 0:
            tysiace_slownie = slownik[tysiace] + " tysiące"
            lista_slow.insert(0,tysiace_slownie)
        if tysiace != 0 and tysiace >= 2 and tysiace < 5 and dziesiatki == 0 and jednosc != 0:
            tysiace_slownie = slownik[tysiace] + " tysiące"
            lista_slow.insert(0,tysiace_slownie)
            lista_slow.append(jednosci_slownie)
    if setki != 0:
        if tysiace != 0 and tysiace >= 2 and tysiace < 5:
            tysiace_slownie = slownik[tysiace] + " tysiące"
            lista_slow.insert(0,tysiace_slownie)

    if setki == 0:
        if tysiace != 0 and tysiace >= 5 and dziesiatki != 0:
           tysiace_slownie = slownik[tysiace] + " tysięcy"
           lista_slow.insert(0,tysiace_slownie)
        if tysiace != 0 and tysiace >= 5 and dziesiatki == 0 and jednosc == 0:
            tysiace_slownie = slownik[tysiace] + " tysięcy"
            lista_slow.insert(0,tysiace_slownie)
        if tysiace != 0 and tysiace >= 5 and dziesiatki == 0 and jednosc != 0:
            tysiace_slownie = slownik[tysiace] + " tysięcy"
            lista_slow.insert(0,tysiace_slownie)
            lista_slow.append(jednosci_slownie)
    if setki != 0:
        if tysiace != 0 and tysiace >= 5:
            tysiace_slownie = slownik[tysiace] + " tysięcy"
            lista_slow.insert(0,tysiace_slownie)

#DZIESIĄTKI TYSIĘCY
    if tysiace == 0:
        if tysiace_dzies != 0 and dziesiatki != 0:
            tysiace_dzies_slownie = slownik[tysiace_dzies] + " tysięcy"
            lista_slow.insert(0,tysiace_dzies_slownie)
        if tysiace_dzies != 0 and dziesiatki == 0 and jednosc == 0:
            tysiace_dzies_slownie = slownik[tysiace_dzies] + " tysięcy"
            lista_slow.insert(0,tysiace_dzies_slownie)
        if tysiace_dzies != 0 and dziesiatki == 0 and jednosc != 0 and setki == 0:
            tysiace_dzies_slownie = slownik[tysiace_dzies] + " tysięcy"
            lista_slow.insert(0,tysiace_dzies_slownie)
            lista_slow.append(jednosci_slownie)
        if tysiace_dzies != 0 and dziesiatki == 0 and jednosc != 0 and setki != 0:
            tysiace_dzies_slownie = slownik[tysiace_dzies] + " tysięcy"
            lista_slow.insert(0,tysiace_dzies_slownie) 
    if tysiace != 0:
        if tysiace_dzies == 10:
            tysiace_dzies_slownie = slownik[tysiace_dzies_nascie] + " tysięcy"
            lista_slow.insert(0,tysiace_dzies_slownie)
            lista_slow.remove(tysiace_slownie)
        if tysiace_dzies >= 20 and tysiace == 1:
            tysiace_dzies_slownie = slownik[tysiace_dzies]
            lista_slow.insert(0,tysiace_dzies_slownie)
            lista_slow.remove(tysiace_slownie)
            reszta_dziel_dzies_tys_slownie = slownik[reszta_dziel_dzies_tys] + " tysięcy"
            lista_slow.insert(1,reszta_dziel_dzies_tys_slownie)
        if tysiace_dzies >= 20 and tysiace >= 2 and tysiace < 5:
            tysiace_dzies_slownie = slownik[tysiace_dzies]
            lista_slow.insert(0,tysiace_dzies_slownie)
            lista_slow.remove(tysiace_slownie)
            reszta_dziel_dzies_tys_slownie = slownik[reszta_dziel_dzies_tys] + " tysiące"
            lista_slow.insert(1,reszta_dziel_dzies_tys_slownie)
        if tysiace_dzies >= 20 and tysiace >= 5:
            tysiace_dzies_slownie = slownik[tysiace_dzies]
            lista_slow.insert(0,tysiace_dzies_slownie)
            lista_slow.remove(tysiace_slownie)
            reszta_dziel_dzies_tys_slownie = slownik[reszta_dziel_dzies_tys] + " tysięcy"
            lista_slow.insert(1,reszta_dziel_dzies_tys_slownie)

#SETKI TYSIĘCY
    if tysiace_set != 0 and tysiace_dzies == 0 and tysiace == 0 and jednosc == 0:
        tysiace_set_slownie = slownik[tysiace_set] + " tysięcy"
        lista_slow.insert(0,tysiace_set_slownie)
    if tysiace_set != 0 and tysiace_dzies == 0 and tysiace == 0 and jednosc != 0 and dziesiatki == 0 and setki == 0:
        tysiace_set_slownie = slownik[tysiace_set] + " tysięcy"
        lista_slow.insert(0,tysiace_set_slownie)
        lista_slow.append(jednosci_slownie)
    if tysiace_set != 0 and tysiace_dzies == 0 and tysiace == 0 and jednosc != 0 and dziesiatki == 0 and setki != 0:
        tysiace_set_slownie = slownik[tysiace_set] + " tysięcy"
        lista_slow.insert(0,tysiace_set_slownie)
    if tysiace_set != 0 and tysiace_dzies == 0 and tysiace == 0 and jednosc != 0 and dziesiatki > 0:
        tysiace_set_slownie = slownik[tysiace_set] + " tysięcy"
        lista_slow.insert(0,tysiace_set_slownie)
    if tysiace_set != 0 and tysiace_dzies == 0 and tysiace == 1:
        tysiace_set_slownie = slownik[tysiace_set]
        lista_slow.insert(0,tysiace_set_slownie)
        lista_slow.remove(tysiace_slownie)
        reszta_dziel_dzies_tys_slownie = slownik[reszta_dziel_dzies_tys] + " tysięcy"
        lista_slow.insert(1,reszta_dziel_dzies_tys_slownie)
    if tysiace_set != 0 and tysiace_dzies == 0 and tysiace >= 2 and tysiace < 5:
        tysiace_set_slownie = slownik[tysiace_set]
        lista_slow.insert(0,tysiace_set_slownie)
        lista_slow.remove(tysiace_slownie)
        reszta_dziel_dzies_tys_slownie = slownik[reszta_dziel_dzies_tys] + " tysiące"
        lista_slow.insert(1,reszta_dziel_dzies_tys_slownie)
    if tysiace_set != 0 and tysiace_dzies == 0 and tysiace >= 5:
        tysiace_set_slownie = slownik[tysiace_set]
        lista_slow.insert(0,tysiace_set_slownie)
        lista_slow.remove(tysiace_slownie)
        reszta_dziel_dzies_tys_slownie = slownik[reszta_dziel_dzies_tys] + " tysięcy"
        lista_slow.insert(1,reszta_dziel_dzies_tys_slownie)
    if tysiace_set != 0 and tysiace_dzies != 0:
        tysiace_set_slownie = slownik[tysiace_set]
        lista_slow.insert(0,tysiace_set_slownie)


    return lista_slow

liczba = int(input("Podaj liczbę całkowitą mniejszą niż milion:"))
if liczba < 1000000:
    lista_slow = zmiana_l(liczba)
    liczba_slownie = " ".join(lista_slow)
    print("Zapis słowny podanej liczby to: ",liczba_slownie)
else:
    liczba = int(input("Nie podałeś liczby całkowitej mniejszej niż 1000000 (milion). Podaj liczbę całkowitą mniejszą niż milion:"))  
    lista_slow = zmiana_l(liczba)
    liczba_slownie = " ".join(lista_slow)
    print("Zapis słowny podanej liczby to: ",liczba_slownie)