# -*- coding: utf-8 -*-
"""szyfruj_lub_deszyfruj_plik.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k7XHn68_-04fVQnLmWdKj3Dt_dSrOmOE

Stworzyć dwie funkcje:

def szyfruj(nazwaWe, przesun)

def deszyfruj(nazwaWe, przesun)

Funkcja szyfruj dokonuje szyfrowania pliku, którego nazwa podana została jako pierwszy parametr. Szyfrowanie polega na zamianie każdej litery na sign przesunięty o wartość podaną drugim parametrem np. dla przesunięcia równego 2 literka ’a’ powinna zostać zastąpiona literką ’c’, literka ’z’ literką ’b’ itp.

Wynikiem działania funkcji ma być plik o nazwie utworzonej na podstawie nazwy
pliku wejściowego poprzez dołączenie signu ’_’ np. dla pliku dane.txt zaszyfrowana postać powinna mieć nazwę _dane.txt. Funkcja deszyfruj powinna deszyfrować plik (niekoniecznie ten sam) zaszyfrowany przez funkcję szyfruj
"""

def szyfruj(nazwaWe,przesun):

    file_content = open(nazwaWe, "r").read()   

    new_file = open("_" + nazwaWe, "w")

    for sign in file_content:
        if sign.isalpha() and sign.isupper():
            sign2 = ord(sign)+przesun
            if sign2 > 90:
                sign2 = sign2 - 26
            new_file.write(chr(sign2))
        elif sign.isalpha() and sign.islower():
            sign2 = ord(sign)+przesun
            if sign2 > 122:
                sign2 = sign2 - 26
            new_file.write(chr(sign2))
        else:
            sign2 = ord(sign)
            new_file.write(chr(sign2))

    new_file.close()  


szyfruj("dane.txt",2)


deszyfr_answer = input("Czy chcesz deszyfrować jakiś plik? Wpisz tak lub nie: ")
if deszyfr_answer == "tak":

    file_to_deszyfr = input("Wpisz nazwę pliku, który chcesz deszyfrować, np: _dane.txt")


#przesunięcie będzie to samo bo deszyfruję plik zaszyfrowany przez funkcję szyfruj (choć nie koniecznie ten sam)

    def deszyfruj(nazwaWe,przesun):

        file_content = open(nazwaWe, "r").read()    
        #print(file_content)

        nazwaWe = nazwaWe.replace("_","") + "_deszyfr"

        new_file_deszyfr = open(nazwaWe, "w")

        for sign in file_content:
            if sign.isalpha() and sign.isupper():
                sign2 = ord(sign)-przesun   
                if sign2 < 65:
                    sign2 = sign2 + 26
                new_file_deszyfr.write(chr(sign2))
            elif sign.isalpha() and sign.islower():
                sign2 = ord(sign)-przesun
                if sign2 < 97:
                    sign2 = sign2 + 26
                new_file_deszyfr.write(chr(sign2))
            else:
                sign2 = ord(sign)
                new_file_deszyfr.write(chr(sign2))


        new_file_deszyfr.close()


    deszyfruj(file_to_deszyfr,2)